### ISSUE TITLE
Prepare infra for collecting metrics from e2e test runs

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#1211]
Right now there is some work going on on exposing metrics via prometheus on kubevirtci clusters. In order to make use of that data, we should provide the infrastructure in our CI environment to allow collecting it and making it easily accessible.

The steps to do that are:

Minimal steps in kubevirt/kubevirtci to allow experimenting:

 - [x] Add an option to `gocli` in kubevirtci to get prometheus up and running and exposed on a node port (@marceloamaral) (https://github.com/kubevirt/kubevirtci/pull/608)
 - [x] Bump kubevirtci to use the new kubevirtci version with the prometheus-operator (https://github.com/kubevirt/kubevirt/pull/5614)
 - [x]  Ensure that kubevirt properly detects the prometheus-operator and automatic metrics collection starts: https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator (https://github.com/kubevirt/kubevirt/pull/5652)
 - [ ] Start collecting at least apiserver metrics from k8s in addition to kubevirt metrics

Minimal steps for kubevirt/project-infra to allow experimenting:

 - [x] Install prometheus via prometheus-operator in our e2e cluster (make it part of the default deploy flows) (https://github.com/kubevirt/project-infra/pull/1218)
 - [x] Create a `PodMonitor` which will scrape all pods with a certain label and a certain port on the `/federate`
 - [x] Create an `Ingress` which allows engineers to run prometheus queries for experimenting with  collected data and dashboards
 - [ ] Get a DNS entry for `Ingress`

**Comment by rmohr** [comment]
@nelsonspbr @ezrasilvera @fgimenez @rthallisey FYI

**Comment by ezrasilvera** [comment]
FYI @marceloamaral

**Comment by marceloamaral** [comment]
Regarding the first part, I submitted[ a PR](https://github.com/kubevirt/kubevirtci/pull/608) enabling Prometheus operator in kubevirt/kubevirtci.
The Prometheus operator is disabled by default, and can be enabled via `KUBEVIRT_DEPLOY_PROMETHEUS="true"` and or, `gocli --enable-prometheus`

All the yamls here are based on the repository [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus), and I included the following components:
* [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator)
* [Prometheus](https://prometheus.io/)
* [Prometheus node-exporter](https://github.com/prometheus/node_exporter)
* [Alertmanager](https://github.com/prometheus/alertmanager) (optional)
* [Grafana](https://grafana.com/) (optional)

To make the deployment as light as possible, I made Grafana and  Alertmanager optional and disabled them by default, since it might be necessary only for the global Prometheus.
```
KUBEVIRT_DEPLOY_PROMETHEUS=${:-false}
KUBEVIRT_PROMETHEUS_REPLICAS=${:-1}
KUBEVIRT_DEPLOY_GRAFANA=${:-false}
```

The KubeVirt metrics monitoring must be enabled when deploying KubeVirt, as explained in the [link](https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator) that you shared.

Finally, I did not configured Grafana dashboards with KubeVirt system components and the VM metrics because they are still not available. But there are some work going on to create such [KubeVirt dashboards](https://github.com/kubevirt/monitoring/tree/main/dashboards).

**Comment by fgimenez** [comment]
Awesome @marceloamaral looks great! I've started with the project-infra changes to deploy prometheus-operator on the e2e cluster https://github.com/kubevirt/project-infra/pull/1218

**Comment by fgimenez** [comment]
Prometheus operator is already deployed in the e2e cluster, will continue preparing the Ingress and PodMonitor.

**Comment by marceloamaral** [comment]
That is great @fgimenez!

Regarding the global prometheus in the e2e cluster, how did you configured the storage and retention time?

I think that a good approach to persist the prometheus data is by using [elasticseach](https://www.elastic.co/jp/blog/how-to-implement-prometheus-long-term-storage-using-elasticsearch), which will also make it more scalable and improve the query efficiency. I have experienced before very slow queries with prometheus...

**Comment by fgimenez** [comment]
> Regarding the global prometheus in the e2e cluster, how did you configured the storage and retention time?

@marceloamaral So far we don't have a cache node in this self-managed cluster, so at the moment storage is kept in an empty-dir configured here https://github.com/kubevirt/project-infra/blob/master/github/ci/services/prometheus-stack/patches/production-e2e-workloads/prometheus-storage.yaml As soon as we are able to create persistent volumes in this cluster (expected to be available this week), we will switch to a PV. Short term we will integrate thanos to aggregate and persist data from the different clusters, we should not have query issues when this is done, but in any case we can integrate other improvements if needed.

**Comment by rmohr** [comment]
@fgimenez do we have an agreement so far that we continue with prometheus-operator inside kubevirtci? If it durns out to not work as well as expected, I have no issues iterating on it later on.

**Comment by nelsonspbr** [comment]
@rmohr @fgimenez @dhiller
Now that the collection infra is in place, @marceloamaral and I were just discussing yesterday about how to implement the prototype. We thought about creating a separate `performance.sh` script under `kubevirt/kubevirt/automation/`. Then we can add the test to `project-infra/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml`, for instance, and test it in CI by submitting a PR. It would be something simple, like creating a couple of VMs and retrieving metrics. We would probably mark it as `always_run: false` and manually trigger it. 

Does this sound like the right approach?

**Comment by rmohr** [comment]
> @rmohr @fgimenez @dhiller
> Now that the collection infra is in place, @marceloamaral and I were just discussing yesterday about how to implement the prototype. We thought about creating a separate `performance.sh` script under `kubevirt/kubevirt/automation/`. Then we can add the test to `project-infra/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml`, for instance, and test it in CI by submitting a PR. It would be something simple, like creating a couple of VMs and retrieving metrics. We would probably mark it as `always_run: false` and manually trigger it.

@nelsonspbr How about chaning `hack/functest.sh` that it skips tests which have a `[performance]` tag by default? You would then only have to export on a job the env variable which starts prometheus and an env variable which focuses on `performance` tests and you can add the performance tests like any other e2e test to our test suite.

**Comment by rmohr** [comment]
@marceloamaral I think we actually forgot the part which makes the services accessible. Would you mind having a look at https://github.com/kubevirt/kubevirtci/pull/614 and verifying if you can access the services through the exposed ports?
