### ISSUE TITLE
Automate release note updates 

### ISSUE THREAD

**Issue by dhiller** [kubevirt/project-infra#2159]
See https://github.com/kubevirt/user-guide/pull/546 for an example of manually updating the user guide with the latest release notes by using the script [`update_changelog.sh`]

To automate this we need to create a postsubmit job that is triggered after every release (meaning after the tagging has finalized) of KubeVirt, calling the script [`update_changelog.sh`] on a fresh checkout and creating a PR with the changes.

See [an example job to base this work on](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-postsubmits.yaml#L3).

/kind enhancement
/area automation

FYI @aburdenthehand

[`update_changelog.sh`]: https://github.com/kubevirt/user-guide/blob/main/update_changelog.sh

**Comment by aburdenthehand** [comment]
@dhiller Does it make sense to change the scope of this issue now that we've changed the release cadence? 
Now, the automation part should be an update to the release notes build so that it filters the release notes based on their /kind and /sig labels. And rather than automate their release, we'll want to have a step to allow manual review and update, since we'll be dealing with much larger sets of release notes.

**Comment by aburdenthehand** [comment]
I'd suggest this could also be included in #2576 
Once the release notes have been reviewed and we publish them for the release, they can also be built for the user guide.
@dhiller wdyt?
