### ISSUE TITLE
Documentation needed: Local testing of website CI/CD

### ISSUE THREAD

**Issue by cwilkers** [kubevirt/project-infra#2368]
The process to test prow containers (whether builds or runs) locally is not well documented.

Key steps include:

- Understanding layout of project-infra repo
- Setting up a github token
- Setting up phaino to locally run prow jobs

**Comment by dhiller** [comment]
Hey @cwilkers, I am not entirely sure whether I understand what this issue is about? Could you elaborate a bit about what the goal would be?

More specific questions - what do you mean by:

# "prow containers"?

I am guessing here that you mean the containers that are used by prow jobs, i.e. the basic bootstrap container, or more specifically all the containers inside https://github.com/kubevirt/project-infra/tree/main/images ?

# setting up a git token

I am guessing that you mean the process of generating a token that you can then use for certain GitHub actions?

# setting up phaino

I think that there is a minimum of docs hidden inside the project-infra repo, somewhere besides robots/cmd/flakefinder, but I guess you are right, more docs is needed here.

/cc @aburdenthehand

**Comment by cwilkers** [comment]
> Hey @cwilkers, I am not entirely sure whether I understand what this issue is about? Could you elaborate a bit about what the goal would be?
> 
> More specific questions - what do you mean by:
> 
> # "prow containers"?
> I am guessing here that you mean the containers that are used by prow jobs, i.e. the basic bootstrap container, or more specifically all the containers inside https://github.com/kubevirt/project-infra/tree/main/images ?

That's correct, I came across this system when trying to validate that the container I was updating to work with both user-guide and kubevirt.github.io repositories' Makefiles was also valid for the CI workflows in project-infra.

> 
> # setting up a git token
> I am guessing that you mean the process of generating a token that you can then use for certain GitHub actions?

Yes, this is part of the prerequisites for Phaino, I believe most of the access required is read-only.

> 
> # setting up phaino
> I think that there is a minimum of docs hidden inside the project-infra repo, somewhere besides robots/cmd/flakefinder, but I guess you are right, more docs is needed here.
> 

This is interesting; the README link I have in my notes for Phaino is now deprecated, and the Phaino docs are part of Prow's docs and can be found at:

https://docs.prow.k8s.io/docs/components/cli-tools/phaino/

I should try going through that again and see if it's more straightforward now. Perhaps they've improved the Phaino documentation enough to eliminate the need for this local documentation beyond some links.

> /cc @aburdenthehand
