### ISSUE TITLE
Eliminate the need to push kubevirtci-core-clusters on PRs to the registry

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#515]
Now with confirmance tests merged we have at least for the core providers a much higher guarantee that they are working. Now is the time where we can start thinking about building and pushing these clusters as postsubmits and e.g. hardcode the cluster-shasums in `gocli`.

@jean-edouard @qinqon you two were pretty interested in this important move. Would you two organize on that?

**Comment by qinqon** [comment]
What pops out of my mind is two possible solutions:
- harcode them to gocli we can pass compilation flags or put them as container flags
- make the postsubmit job generate a release tarball at github release page with cluster-up scripts + images.

**Comment by qinqon** [comment]
I have do the following PR to store shas at gocli binary and remove images.sh https://github.com/kubevirt/kubevirtci/pull/403

The idea is to has at github release page a tarball with gocli binary and helper bash scripts and that's what people use at project.

About kubevirtci dev experience we can make a fallback at scrits at build gocli if it's not present and take latest provider images (since there is not going to be a manual push-k8s) latest would be fine (they would be lasted stuff merged to master)

Also in case of iterating on provider container we need something to override those.

**Comment by qinqon** [comment]
The presubmit job `release-kubevirtci` job is working fine now https://prow.apps.ovirt.org/?job=release-kubevirtci it also stores the kubevirtci tarball at artifacts so we can test if it works https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/403/release-kubevirtci/1285577459806244864/artifacts/kubevirtci.tar

Stuff missing:
- How to identify what clusters to provision
- Do the github release part.
